export const footerLinks = [
  "About",
  "Blog",
  "Jobs",
  "Help",
  "API",
  "Privacy",
  "Terms",
  "Locations",
  "Snaply Lite",
  "Snaply AI",
  "Snaply AI Articles",
  "Threads",
  "Contact Uploading & Non-Users",
  "Snaply Verified",
];
