import { useGLTF } from "@react-three/drei";
import { useFrame } from "@react-three/fiber";
import { RigidBody } from "@react-three/rapier";
import { useEffect, useRef } from "react";
import { Vector3, Quaternion } from "three";

export function Car(props) {
  const keys = useRef({
    w: false,
    a: false,
    s: false,
    d: false,
  });

  useFrame(() => {
    const rotation = carRef.current.rotation();
    const forward = new Vector3(0, 0, 1);
    const quat = new Quaternion(rotation.x, rotation.y, rotation.z, rotation.w);
    forward.applyQuaternion(quat);

    if (keys.current["w"]) {
      carRef.current.applyImpulse(
        { x: forward.x * 3, y: 0, z: forward.z * 2 },
        true,
      );
    }
    if (keys.current["s"]) {
      carRef.current.applyImpulse(
        { x: -forward.x * 3, y: 0, z: -forward.z * 2 },
        true,
      );
    }
    if (keys.current["a"]) {
      carRef.current.applyTorqueImpulse({ x: 0, y: 0.5, z: 0 }, true);
    }
    if (keys.current["d"]) {
      carRef.current.applyTorqueImpulse({ x: 0, y: -0.5, z: 0 }, true);
    }
    // const pos = carRef.current.translation();
    // camera.position.set(pos.x, pos.y + 5, pos.z - 5);
    // camera.lookAt(pos.x, pos.y, pos.z);
  });

  useEffect(() => {
    const onKeyDown = (e) => {
      keys.current[e.key] = true;
    };
    const onKeyUp = (e) => {
      keys.current[e.key] = false;
    };
    document.addEventListener("keydown", onKeyDown);
    document.addEventListener("keyup", onKeyUp);
    return () => {
      document.removeEventListener("keydown", onKeyDown);
      document.removeEventListener("keyup", onKeyUp);
    };
  }, []);

  const { nodes, materials } = useGLTF("/1970_chevrolet_chevelle_ss_454.glb");
  const carRef = useRef(null);
  return (
    <RigidBody
      linearDamping={0.5}
      angularDamping={0.5}
      type="dynamic"
      colliders="hull"
      position={[0, 2, 0]}
      ref={carRef}
    >
      return (
      <group {...props} dispose={null}>
        <group scale={0.01}>
          <group
            position={[0, 0.27, -0.178]}
            rotation={[-Math.PI, 0, -Math.PI]}
          >
            <mesh
              castShadow
              receiveShadow
              geometry={
                nodes
                  .che_chevelle_70_rotorrf_lod0che_chevelle_70_rotorrf_lod0_rotorRF_rotor_170vertices167faces_Ext_Metal_0
                  .geometry
              }
              material={materials.Ext_Metal}
              position={[0.597, 0.055, -1.621]}
              scale={[1.07, 0.965, 0.965]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={
                nodes
                  .che_chevelle_70_caliperlf_lod0che_chevelle_70_caliperlf_lod0_caliperLF_caliper_700vertices695faces_Ext_Metal_0
                  .geometry
              }
              material={materials.Ext_Metal}
              position={[-0.597, 0.055, -1.621]}
              scale={[1.07, 0.965, 0.965]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={
                nodes
                  .che_chevelle_70_rotorrf_lod0che_chevelle_70_rotorrf_lod0_rotorRF_hub_129vertices193faces_Ext_Metal_0
                  .geometry
              }
              material={materials.Ext_Metal}
              position={[0.597, 0.055, -1.621]}
              scale={[1.07, 0.965, 0.965]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={
                nodes
                  .che_chevelle_70_rotorlf_lod0che_chevelle_70_rotorlf_lod0_rotorLF_hub_129vertices192faces_Ext_Metal_0
                  .geometry
              }
              material={materials.Ext_Metal}
              position={[-0.597, 0.055, -1.621]}
              scale={[1.07, 0.965, 0.965]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={
                nodes
                  .che_chevelle_70_rotorlf_lod0che_chevelle_70_rotorlf_lod0_rotorLF_rotor_170vertices163faces_Ext_Metal_0
                  .geometry
              }
              material={materials.Ext_Metal}
              position={[-0.597, 0.055, -1.621]}
              scale={[1.07, 0.965, 0.965]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={
                nodes
                  .che_chevelle_70_caliperrf_lod0che_chevelle_70_caliperrf_lod0_caliperRF_misc_574vertices579faces_Ext_Metal_0
                  .geometry
              }
              material={materials.Ext_Metal}
              position={[0.597, 0.055, -1.621]}
              scale={[1.07, 0.965, 0.965]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={
                nodes
                  .che_chevelle_70_caliperrf_lod0che_chevelle_70_caliperrf_lod0_caliperRF_matte_colors_130vertices125faces_Ext_Metal_0
                  .geometry
              }
              material={materials.Ext_Metal}
              position={[0.597, 0.055, -1.621]}
              scale={[1.07, 0.965, 0.965]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={
                nodes
                  .che_chevelle_70_cockpitche_chevelle_70_cockpit_tach_min_plastic_80vertices80faces_INT_Plastic_0
                  .geometry
              }
              material={materials.INT_Plastic}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={
                nodes
                  .che_chevelle_70_cockpitche_chevelle_70_cockpit_tach_min_gauge_needle_28vertices18faces_int_Metal_0
                  .geometry
              }
              material={materials.int_Metal}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={
                nodes
                  .che_chevelle_70_cockpitche_chevelle_70_cockpit_tach_min_chrome_20vertices18faces_Ext_Metal_0
                  .geometry
              }
              material={materials.Ext_Metal}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={
                nodes
                  .che_chevelle_70_cockpitche_chevelle_70_cockpit_tach_mid_plastic_80vertices80faces_INT_Plastic_0
                  .geometry
              }
              material={materials.INT_Plastic}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={
                nodes
                  .che_chevelle_70_cockpitche_chevelle_70_cockpit_tach_mid_gauge_needle_28vertices18faces_int_Metal_0
                  .geometry
              }
              material={materials.int_Metal}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={
                nodes
                  .che_chevelle_70_cockpitche_chevelle_70_cockpit_tach_mid_chrome_20vertices18faces_Ext_Metal_0
                  .geometry
              }
              material={materials.Ext_Metal}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={
                nodes
                  .che_chevelle_70_cockpitche_chevelle_70_cockpit_tach_max_plastic_80vertices80faces_INT_Plastic_0
                  .geometry
              }
              material={materials.INT_Plastic}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={
                nodes
                  .che_chevelle_70_cockpitche_chevelle_70_cockpit_tach_max_gauge_needle_28vertices18faces_int_Metal_0
                  .geometry
              }
              material={materials.int_Metal}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={
                nodes
                  .che_chevelle_70_cockpitche_chevelle_70_cockpit_tach_max_chrome_20vertices18faces_Ext_Metal_0
                  .geometry
              }
              material={materials.Ext_Metal}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={
                nodes
                  .che_chevelle_70_cockpitche_chevelle_70_cockpit_steering_wheel_plastic_3152vertices5466faces_INT_Plastic_0
                  .geometry
              }
              material={materials.INT_Plastic}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={
                nodes
                  .che_chevelle_70_cockpitche_chevelle_70_cockpit_steering_wheel_chrome_694vertices715faces_Ext_Metal_0
                  .geometry
              }
              material={materials.Ext_Metal}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={
                nodes
                  .che_chevelle_70_cockpitche_chevelle_70_cockpit_steering_wheel_bump_plastic_147vertices145faces_INT_Plastic_0
                  .geometry
              }
              material={materials.INT_Plastic}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={
                nodes
                  .che_chevelle_70_cockpitche_chevelle_70_cockpit_speed_min_gauge_needle_14vertices6faces_int_Metal_0
                  .geometry
              }
              material={materials.int_Metal}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={
                nodes
                  .che_chevelle_70_cockpitche_chevelle_70_cockpit_speed_min_chrome_60vertices58faces_Ext_Metal_0
                  .geometry
              }
              material={materials.Ext_Metal}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={
                nodes
                  .che_chevelle_70_cockpitche_chevelle_70_cockpit_speed_mid_gauge_needle_14vertices6faces_int_Metal_0
                  .geometry
              }
              material={materials.int_Metal}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={
                nodes
                  .che_chevelle_70_cockpitche_chevelle_70_cockpit_speed_mid_chrome_60vertices58faces_Ext_Metal_0
                  .geometry
              }
              material={materials.Ext_Metal}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={
                nodes
                  .che_chevelle_70_cockpitche_chevelle_70_cockpit_speed_max_gauge_needle_14vertices6faces_int_Metal_0
                  .geometry
              }
              material={materials.int_Metal}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={
                nodes
                  .che_chevelle_70_cockpitche_chevelle_70_cockpit_speed_max_chrome_60vertices58faces_Ext_Metal_0
                  .geometry
              }
              material={materials.Ext_Metal}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={
                nodes
                  .che_chevelle_70_cockpitche_chevelle_70_cockpit_seatR_plastic_108vertices118faces_INT_Plastic_0
                  .geometry
              }
              material={materials.INT_Plastic}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={
                nodes
                  .che_chevelle_70_cockpitche_chevelle_70_cockpit_seatR_leather_2007vertices2747faces_INT_Leather_0
                  .geometry
              }
              material={materials.INT_Leather}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={
                nodes
                  .che_chevelle_70_cockpitche_chevelle_70_cockpit_seatR_cloth_132vertices132faces_Int_cloth_0
                  .geometry
              }
              material={materials.Int_cloth}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={
                nodes
                  .che_chevelle_70_cockpitche_chevelle_70_cockpit_seatR_chrome_26vertices18faces_Ext_Metal_0
                  .geometry
              }
              material={materials.Ext_Metal}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={
                nodes
                  .che_chevelle_70_cockpitche_chevelle_70_cockpit_seatL_plastic_108vertices118faces_INT_Plastic_0
                  .geometry
              }
              material={materials.INT_Plastic}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={
                nodes
                  .che_chevelle_70_cockpitche_chevelle_70_cockpit_seatL_leather_2007vertices2824faces_INT_Leather_0
                  .geometry
              }
              material={materials.INT_Leather}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={
                nodes
                  .che_chevelle_70_cockpitche_chevelle_70_cockpit_seatL_cloth_97vertices92faces_Int_cloth_0
                  .geometry
              }
              material={materials.Int_cloth}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={
                nodes
                  .che_chevelle_70_cockpitche_chevelle_70_cockpit_seatL_chrome_26vertices17faces_Ext_Metal_0
                  .geometry
              }
              material={materials.Ext_Metal}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={
                nodes
                  .che_chevelle_70_cockpitche_chevelle_70_cockpit_mirrorL_rubber_trim_118vertices110faces_rubber_0
                  .geometry
              }
              material={materials.rubber}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={
                nodes
                  .che_chevelle_70_cockpitche_chevelle_70_cockpit_mirrorL_mirrorLeft_53vertices103faces_mirror_0
                  .geometry
              }
              material={materials.mirror}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={
                nodes
                  .che_chevelle_70_cockpitche_chevelle_70_cockpit_mirrorL_matte_colors_37vertices45faces_EXT_0
                  .geometry
              }
              material={materials.material}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={
                nodes
                  .che_chevelle_70_cockpitche_chevelle_70_cockpit_mirrorL_chrome_1034vertices2003faces_Ext_Metal_0
                  .geometry
              }
              material={materials.Ext_Metal}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={
                nodes
                  .che_chevelle_70_cockpitche_chevelle_70_cockpit_interior_solid_70vertices48faces_INT_Plastic_0
                  .geometry
              }
              material={materials.INT_Plastic}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={
                nodes
                  .che_chevelle_70_cockpitche_chevelle_70_cockpit_interior_rubber_495vertices648faces_rubber_0
                  .geometry
              }
              material={materials.rubber}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={
                nodes
                  .che_chevelle_70_cockpitche_chevelle_70_cockpit_interior_reflector_89vertices132faces_int_Metal_0
                  .geometry
              }
              material={materials.int_Metal}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={
                nodes
                  .che_chevelle_70_cockpitche_chevelle_70_cockpit_interior_plastic_8642vertices9762faces_INT_Plastic_0
                  .geometry
              }
              material={materials.INT_Plastic}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={
                nodes
                  .che_chevelle_70_cockpitche_chevelle_70_cockpit_interior_mottled_182vertices289faces_Int_cloth_0
                  .geometry
              }
              material={materials.Int_cloth}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={
                nodes
                  .che_chevelle_70_cockpitche_chevelle_70_cockpit_interior_mirrorMiddle_26vertices32faces_mirror_0
                  .geometry
              }
              material={materials.mirror}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={
                nodes
                  .che_chevelle_70_cockpitche_chevelle_70_cockpit_interior_metal_4458vertices5108faces_int_Metal_0
                  .geometry
              }
              material={materials.int_Metal}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={
                nodes
                  .che_chevelle_70_cockpitche_chevelle_70_cockpit_interior_leather_2630vertices3658faces_INT_Leather_0
                  .geometry
              }
              material={materials.INT_Leather}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={
                nodes
                  .che_chevelle_70_cockpitche_chevelle_70_cockpit_interior_headliner_241vertices442faces_Int_cloth_0
                  .geometry
              }
              material={materials.Int_cloth}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={
                nodes
                  .che_chevelle_70_cockpitche_chevelle_70_cockpit_interior_glass_198vertices339faces_int_glass_0
                  .geometry
              }
              material={materials.int_glass}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={
                nodes
                  .che_chevelle_70_cockpitche_chevelle_70_cockpit_interior_gauge_needle_74vertices36faces_int_Metal_0
                  .geometry
              }
              material={materials.int_Metal}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={
                nodes
                  .che_chevelle_70_cockpitche_chevelle_70_cockpit_interior_cloth_172vertices156faces_Int_cloth_0
                  .geometry
              }
              material={materials.Int_cloth}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={
                nodes
                  .che_chevelle_70_cockpitche_chevelle_70_cockpit_interior_chrome_6436vertices7797faces_Ext_Metal_0
                  .geometry
              }
              material={materials.Ext_Metal}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={
                nodes
                  .che_chevelle_70_cockpitche_chevelle_70_cockpit_interior_bump_plastic2_737vertices1387faces_INT_Plastic_0
                  .geometry
              }
              material={materials.INT_Plastic}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={
                nodes
                  .che_chevelle_70_cockpitche_chevelle_70_cockpit_interior_bump_plastic_1882vertices2932faces_INT_Plastic_0
                  .geometry
              }
              material={materials.INT_Plastic}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={
                nodes
                  .che_chevelle_70_cockpitche_chevelle_70_cockpit_interior_bump_leather3_1528vertices2306faces_INT_Leather_0
                  .geometry
              }
              material={materials.INT_Leather}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={
                nodes
                  .che_chevelle_70_cockpitche_chevelle_70_cockpit_interior_badge_220vertices135faces_INt_T_0
                  .geometry
              }
              material={materials.INt_T}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={
                nodes
                  .che_chevelle_70_cockpitche_chevelle_70_cockpit_hooda_vent_matte_colors_120vertices60faces_EXT_0
                  .geometry
              }
              material={materials.material}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={
                nodes
                  .che_chevelle_70_cockpitche_chevelle_70_cockpit_hooda_vent_body_269vertices221faces_CarPaint_0
                  .geometry
              }
              material={materials.CarPaint}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={
                nodes
                  .che_chevelle_70_cockpitche_chevelle_70_cockpit_hooda_vent_black_119vertices48faces_EXT_0
                  .geometry
              }
              material={materials.material}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={
                nodes
                  .che_chevelle_70_cockpitche_chevelle_70_cockpit_hooda_matte_colors_883vertices1326faces_EXT_0
                  .geometry
              }
              material={materials.material}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={
                nodes
                  .che_chevelle_70_cockpitche_chevelle_70_cockpit_hooda_frame_204vertices306faces_EXT_0
                  .geometry
              }
              material={materials.material}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={
                nodes
                  .che_chevelle_70_cockpitche_chevelle_70_cockpit_hooda_chrome_4309vertices5506faces_Ext_Metal_0
                  .geometry
              }
              material={materials.Ext_Metal}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={
                nodes
                  .che_chevelle_70_cockpitche_chevelle_70_cockpit_hooda_body_1904vertices4579faces_CarPaint_0
                  .geometry
              }
              material={materials.CarPaint}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={
                nodes
                  .che_chevelle_70_cockpitche_chevelle_70_cockpit_glassRF_window_72vertices110faces_window_0
                  .geometry
              }
              material={materials.window}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={
                nodes
                  .che_chevelle_70_cockpitche_chevelle_70_cockpit_glassLF_window_72vertices106faces_window_0
                  .geometry
              }
              material={materials.window}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={
                nodes
                  .che_chevelle_70_cockpitche_chevelle_70_cockpit_glassF_window_144vertices299faces_window_0
                  .geometry
              }
              material={materials.window}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={
                nodes
                  .che_chevelle_70_cockpitche_chevelle_70_cockpit_fuel_min_gauge_needle_14vertices6faces_int_Metal_0
                  .geometry
              }
              material={materials.int_Metal}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={
                nodes
                  .che_chevelle_70_cockpitche_chevelle_70_cockpit_fuel_min_chrome_36vertices35faces_Ext_Metal_0
                  .geometry
              }
              material={materials.Ext_Metal}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={
                nodes
                  .che_chevelle_70_cockpitche_chevelle_70_cockpit_fuel_mid_gauge_needle_14vertices6faces_int_Metal_0
                  .geometry
              }
              material={materials.int_Metal}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={
                nodes
                  .che_chevelle_70_cockpitche_chevelle_70_cockpit_fuel_mid_chrome_36vertices35faces_Ext_Metal_0
                  .geometry
              }
              material={materials.Ext_Metal}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={
                nodes
                  .che_chevelle_70_cockpitche_chevelle_70_cockpit_fuel_max_gauge_needle_14vertices6faces_int_Metal_0
                  .geometry
              }
              material={materials.int_Metal}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={
                nodes
                  .che_chevelle_70_cockpitche_chevelle_70_cockpit_fuel_max_chrome_36vertices35faces_Ext_Metal_0
                  .geometry
              }
              material={materials.Ext_Metal}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={
                nodes
                  .che_chevelle_70_lod0che_chevelle_70_lod0_wheel_wheel_black_160vertices173faces_rim_0
                  .geometry
              }
              material={materials.material_12}
              position={[-0.692, 0.055, -1.621]}
              scale={[1.199, 1.081, 1.081]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={
                nodes
                  .che_chevelle_70_lod0che_chevelle_70_lod0_wheel_rim_3421vertices4303faces_rim_0
                  .geometry
              }
              material={materials.material_12}
              position={[-0.692, 0.055, -1.621]}
              scale={[1.199, 1.081, 1.081]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={
                nodes
                  .che_chevelle_70_lod0che_chevelle_70_lod0_wheel_outer_rim_480vertices518faces_rim_0
                  .geometry
              }
              material={materials.material_12}
              position={[-0.692, 0.055, -1.621]}
              scale={[1.199, 1.081, 1.081]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={
                nodes
                  .che_chevelle_70_lod0che_chevelle_70_lod0_wheel_inner_rim_540vertices625faces_rim_0
                  .geometry
              }
              material={materials.material_12}
              position={[-0.692, 0.055, -1.621]}
              scale={[1.199, 1.081, 1.081]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={
                nodes
                  .che_chevelle_70_lod0che_chevelle_70_lod0_undercarriagea_undercarriage_2099vertices2810faces_under_0
                  .geometry
              }
              material={materials.under}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={
                nodes
                  .che_chevelle_70_lod0che_chevelle_70_lod0_trunk_rubber_trim_40vertices43faces_rubber_0
                  .geometry
              }
              material={materials.rubber}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={
                nodes
                  .che_chevelle_70_lod0che_chevelle_70_lod0_trunk_frame_85vertices113faces_EXT_0
                  .geometry
              }
              material={materials.material}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={
                nodes
                  .che_chevelle_70_lod0che_chevelle_70_lod0_trunk_emblem_80vertices160faces_Ext_Metal_0
                  .geometry
              }
              material={materials.Ext_Metal}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={
                nodes
                  .che_chevelle_70_lod0che_chevelle_70_lod0_trunk_chrome_1483vertices1574faces_Ext_Metal_0
                  .geometry
              }
              material={materials.Ext_Metal}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={
                nodes
                  .che_chevelle_70_lod0che_chevelle_70_lod0_trunk_body_764vertices1668faces_CarPaint_0
                  .geometry
              }
              material={materials.CarPaint}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={
                nodes
                  .che_chevelle_70_lod0che_chevelle_70_lod0_trunk_black_107vertices143faces_EXT_0
                  .geometry
              }
              material={materials.material}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={
                nodes
                  .che_chevelle_70_lod0che_chevelle_70_lod0_glassRTL_detail_glass_red_52vertices85faces_Ligth_glass_0
                  .geometry
              }
              material={materials.Ligth_glass}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={
                nodes
                  .che_chevelle_70_lod0che_chevelle_70_lod0_glassRTL_detail_glass_clear_24vertices38faces_Ligth_glass_0
                  .geometry
              }
              material={materials.Ligth_glass}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={
                nodes
                  .che_chevelle_70_lod0che_chevelle_70_lod0_glassRR_window_76vertices129faces_window_0
                  .geometry
              }
              material={materials.window}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={
                nodes
                  .che_chevelle_70_lod0che_chevelle_70_lod0_glassRHL_detail_glass_clear_362vertices712faces_Ligth_glass_0
                  .geometry
              }
              material={materials.Ligth_glass}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={
                nodes
                  .che_chevelle_70_lod0che_chevelle_70_lod0_glassR_window_220vertices404faces_window_0
                  .geometry
              }
              material={materials.window}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={
                nodes
                  .che_chevelle_70_lod0che_chevelle_70_lod0_glassLTL_detail_glass_red_53vertices84faces_Ligth_glass_0
                  .geometry
              }
              material={materials.Ligth_glass}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={
                nodes
                  .che_chevelle_70_lod0che_chevelle_70_lod0_glassLTL_detail_glass_clear_27vertices48faces_Ligth_glass_0
                  .geometry
              }
              material={materials.Ligth_glass}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={
                nodes
                  .che_chevelle_70_lod0che_chevelle_70_lod0_glassLR_window_76vertices129faces_window_0
                  .geometry
              }
              material={materials.window}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={
                nodes
                  .che_chevelle_70_lod0che_chevelle_70_lod0_glassLHL_detail_glass_clear_362vertices714faces_Ligth_glass_0
                  .geometry
              }
              material={materials.Ligth_glass}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={
                nodes
                  .che_chevelle_70_lod0che_chevelle_70_lod0_exhaustRa_matte_colors_402vertices391faces_Ext_Metal_0
                  .geometry
              }
              material={materials.Ext_Metal}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={
                nodes
                  .che_chevelle_70_lod0che_chevelle_70_lod0_exhaustRa_chrome_234vertices441faces_Ext_Metal_0
                  .geometry
              }
              material={materials.Ext_Metal}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={
                nodes
                  .che_chevelle_70_lod0che_chevelle_70_lod0_exhaustRa_black_27vertices46faces_EXT_0
                  .geometry
              }
              material={materials.material}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={
                nodes
                  .che_chevelle_70_lod0che_chevelle_70_lod0_exhaustLa_matte_colors_403vertices385faces_Ext_Metal_0
                  .geometry
              }
              material={materials.Ext_Metal}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={
                nodes
                  .che_chevelle_70_lod0che_chevelle_70_lod0_exhaustLa_chrome_234vertices416faces_Ext_Metal_0
                  .geometry
              }
              material={materials.Ext_Metal}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={
                nodes
                  .che_chevelle_70_lod0che_chevelle_70_lod0_exhaustLa_black_27vertices46faces_EXT_0
                  .geometry
              }
              material={materials.material}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={
                nodes
                  .che_chevelle_70_lod0che_chevelle_70_lod0_bumperRa_textured_reflector_150vertices183faces_light_0
                  .geometry
              }
              material={materials.light}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={
                nodes
                  .che_chevelle_70_lod0che_chevelle_70_lod0_bumperRa_tail_light_lod0_86vertices121faces_light_0
                  .geometry
              }
              material={materials.light}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={
                nodes
                  .che_chevelle_70_lod0che_chevelle_70_lod0_bumperRa_reverse_light_lod0_174vertices208faces_light_0
                  .geometry
              }
              material={materials.light}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={
                nodes
                  .che_chevelle_70_lod0che_chevelle_70_lod0_bumperRa_plastic2_123vertices202faces_EXT_Plsatic_0
                  .geometry
              }
              material={materials.EXT_Plsatic}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={
                nodes
                  .che_chevelle_70_lod0che_chevelle_70_lod0_bumperRa_matte_colors_923vertices1067faces_Ext_Metal_0
                  .geometry
              }
              material={materials.Ext_Metal}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={
                nodes
                  .che_chevelle_70_lod0che_chevelle_70_lod0_bumperRa_detail_glass_red_1440vertices1560faces_Ligth_glass_0
                  .geometry
              }
              material={materials.Ligth_glass}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={
                nodes
                  .che_chevelle_70_lod0che_chevelle_70_lod0_bumperRa_detail_glass_clear_462vertices660faces_Ligth_glass_0
                  .geometry
              }
              material={materials.Ligth_glass}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={
                nodes
                  .che_chevelle_70_lod0che_chevelle_70_lod0_bumperRa_chrome_4949vertices9828faces_Ext_Metal_0
                  .geometry
              }
              material={materials.Ext_Metal}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={
                nodes
                  .che_chevelle_70_lod0che_chevelle_70_lod0_bumperFa_rubber_trim_96vertices104faces_rubber_0
                  .geometry
              }
              material={materials.rubber}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={
                nodes
                  .che_chevelle_70_lod0che_chevelle_70_lod0_bumperFa_matte_colors_300vertices284faces_Ext_Metal_0
                  .geometry
              }
              material={materials.Ext_Metal}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={
                nodes
                  .che_chevelle_70_lod0che_chevelle_70_lod0_bumperFa_head_light_274vertices376faces_light_0
                  .geometry
              }
              material={materials.light}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={
                nodes
                  .che_chevelle_70_lod0che_chevelle_70_lod0_bumperFa_glass_116vertices190faces_int_glass_0
                  .geometry
              }
              material={materials.int_glass}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={
                nodes
                  .che_chevelle_70_lod0che_chevelle_70_lod0_bumperFa_detail_glass_clear_2088vertices2436faces_Ligth_glass_0
                  .geometry
              }
              material={materials.Ligth_glass}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={
                nodes
                  .che_chevelle_70_lod0che_chevelle_70_lod0_bumperFa_chrome_3104vertices7143faces_Ext_Metal_0
                  .geometry
              }
              material={materials.Ext_Metal}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={
                nodes
                  .che_chevelle_70_lod0che_chevelle_70_lod0_body_weatherstrip_1689vertices1627faces_Ext_Metal_0
                  .geometry
              }
              material={materials.Ext_Metal}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={
                nodes
                  .che_chevelle_70_lod0che_chevelle_70_lod0_body_rubber_trim_1038vertices1362faces_rubber_0
                  .geometry
              }
              material={materials.rubber}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={
                nodes
                  .che_chevelle_70_lod0che_chevelle_70_lod0_body_reflector_242vertices217faces_light_0
                  .geometry
              }
              material={materials.light}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={
                nodes
                  .che_chevelle_70_lod0che_chevelle_70_lod0_body_plastic2_1210vertices1471faces_EXT_Plsatic_0
                  .geometry
              }
              material={materials.EXT_Plsatic}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={
                nodes
                  .che_chevelle_70_lod0che_chevelle_70_lod0_body_matte_colors_740vertices900faces_Ext_Metal_0
                  .geometry
              }
              material={materials.Ext_Metal}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={
                nodes
                  .che_chevelle_70_lod0che_chevelle_70_lod0_body_lights_glass_7128vertices9826faces_Ligth_glass_0
                  .geometry
              }
              material={materials.Ligth_glass}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={
                nodes
                  .che_chevelle_70_lod0che_chevelle_70_lod0_body_head_light_336vertices644faces_light_0
                  .geometry
              }
              material={materials.light}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={
                nodes
                  .che_chevelle_70_lod0che_chevelle_70_lod0_body_frame_354vertices419faces_EXT_0
                  .geometry
              }
              material={materials.material}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={
                nodes
                  .che_chevelle_70_lod0che_chevelle_70_lod0_body_emblem_1847vertices2439faces_Ext_Metal_0
                  .geometry
              }
              material={materials.Ext_Metal}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={
                nodes
                  .che_chevelle_70_lod0che_chevelle_70_lod0_body_chrome_16436vertices27616faces_Ext_Metal_0
                  .geometry
              }
              material={materials.Ext_Metal}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={
                nodes
                  .che_chevelle_70_lod0che_chevelle_70_lod0_body_body_16520vertices36341faces_CarPaint_0
                  .geometry
              }
              material={materials.CarPaint}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={
                nodes
                  .che_chevelle_70_lod0che_chevelle_70_lod0_body_black_3031vertices4217faces_EXT_0
                  .geometry
              }
              material={materials.material}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={
                nodes
                  .che_chevelle_70_lod0_wheel_inner_rim_540vertices625faces_rim_0
                  .geometry
              }
              material={materials.material_12}
              position={[0.692, 0.055, -1.621]}
              rotation={[Math.PI, 0, -Math.PI]}
              scale={[1.199, 1.081, 1.081]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={
                nodes
                  .che_chevelle_70_lod0_wheel_wheel_black_160vertices173faces_rim_0
                  .geometry
              }
              material={materials.material_12}
              position={[0.692, 0.055, -1.621]}
              rotation={[Math.PI, 0, -Math.PI]}
              scale={[1.199, 1.081, 1.081]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={
                nodes
                  .che_chevelle_70_lod0_wheel_outer_rim_480vertices518faces_rim_0
                  .geometry
              }
              material={materials.material_12}
              position={[0.692, 0.055, -1.621]}
              rotation={[Math.PI, 0, -Math.PI]}
              scale={[1.199, 1.081, 1.081]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={
                nodes.che_chevelle_70_lod0_wheel_rim_3421vertices4303faces_rim_0
                  .geometry
              }
              material={materials.material_12}
              position={[0.692, 0.055, -1.621]}
              rotation={[Math.PI, 0, -Math.PI]}
              scale={[1.199, 1.081, 1.081]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={
                nodes
                  .che_chevelle_70_lod0_wheel_inner_rim_540vertices625faces1_rim_0
                  .geometry
              }
              material={materials.material_12}
              position={[-0.717, 0.055, 1.271]}
              scale={[1.199, 1.081, 1.081]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={
                nodes
                  .che_chevelle_70_lod0_wheel_outer_rim_480vertices518faces1_rim_0
                  .geometry
              }
              material={materials.material_12}
              position={[-0.717, 0.055, 1.271]}
              scale={[1.199, 1.081, 1.081]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={
                nodes
                  .che_chevelle_70_lod0_wheel_rim_3421vertices4303faces1_rim_0
                  .geometry
              }
              material={materials.material_12}
              position={[-0.717, 0.055, 1.271]}
              scale={[1.199, 1.081, 1.081]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={
                nodes
                  .che_chevelle_70_lod0_wheel_wheel_black_160vertices173faces1_rim_0
                  .geometry
              }
              material={materials.material_12}
              position={[-0.717, 0.055, 1.271]}
              scale={[1.199, 1.081, 1.081]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={
                nodes
                  .che_chevelle_70_lod0_wheel_inner_rim_540vertices625faces2_rim_0
                  .geometry
              }
              material={materials.material_12}
              position={[0.717, 0.055, 1.271]}
              rotation={[Math.PI, 0, -Math.PI]}
              scale={[1.199, 1.081, 1.081]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={
                nodes
                  .che_chevelle_70_lod0_wheel_outer_rim_480vertices518faces2_rim_0
                  .geometry
              }
              material={materials.material_12}
              position={[0.717, 0.055, 1.271]}
              rotation={[Math.PI, 0, -Math.PI]}
              scale={[1.199, 1.081, 1.081]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={
                nodes
                  .che_chevelle_70_lod0_wheel_rim_3421vertices4303faces2_rim_0
                  .geometry
              }
              material={materials.material_12}
              position={[0.717, 0.055, 1.271]}
              rotation={[Math.PI, 0, -Math.PI]}
              scale={[1.199, 1.081, 1.081]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={
                nodes
                  .che_chevelle_70_lod0_wheel_wheel_black_160vertices173faces2_rim_0
                  .geometry
              }
              material={materials.material_12}
              position={[0.717, 0.055, 1.271]}
              rotation={[Math.PI, 0, -Math.PI]}
              scale={[1.199, 1.081, 1.081]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={
                nodes
                  .che_chevelle_70_caliperrf_lod0_caliperRF_misc_574vertices579faces_Ext_Metal_0
                  .geometry
              }
              material={materials.Ext_Metal}
              position={[0.623, 0.055, 1.271]}
              scale={[1.07, 0.965, 0.965]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={
                nodes
                  .che_chevelle_70_caliperrf_lod0_caliperRF_matte_colors_130vertices125faces_Ext_Metal_0
                  .geometry
              }
              material={materials.Ext_Metal}
              position={[0.623, 0.055, 1.271]}
              scale={[1.07, 0.965, 0.965]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={
                nodes
                  .che_chevelle_70_rotorrf_lod0_rotorRF_rotor_170vertices167faces_Ext_Metal_0
                  .geometry
              }
              material={materials.Ext_Metal}
              position={[0.623, 0.055, 1.271]}
              scale={[1.07, 0.965, 0.965]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={
                nodes
                  .che_chevelle_70_rotorrf_lod0_rotorRF_hub_129vertices193faces_Ext_Metal_0
                  .geometry
              }
              material={materials.Ext_Metal}
              position={[0.623, 0.055, 1.271]}
              scale={[1.07, 0.965, 0.965]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={
                nodes
                  .che_chevelle_70_caliperlf_lod0_caliperLF_caliper_700vertices695faces_Ext_Metal_0
                  .geometry
              }
              material={materials.Ext_Metal}
              position={[-0.623, 0.055, 1.271]}
              scale={[1.07, 0.965, 0.965]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={
                nodes
                  .che_chevelle_70_rotorlf_lod0_rotorLF_hub_129vertices192faces_Ext_Metal_0
                  .geometry
              }
              material={materials.Ext_Metal}
              position={[-0.623, 0.055, 1.271]}
              scale={[1.07, 0.965, 0.965]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={
                nodes
                  .che_chevelle_70_rotorlf_lod0_rotorLF_rotor_170vertices163faces_Ext_Metal_0
                  .geometry
              }
              material={materials.Ext_Metal}
              position={[-0.623, 0.055, 1.271]}
              scale={[1.07, 0.965, 0.965]}
            />
          </group>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.zWheel5A_LF_Wheel5A_zWheel5A1_0.geometry}
            material={materials.zWheel5A1}
            position={[-0.217, 0, 0]}
            scale={[1.313, 1, 1]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.zWheel5A_LR_Wheel5A_zWheel5A1_0.geometry}
            material={materials.zWheel5A1}
            position={[-0.225, 0, 0]}
            scale={[1.313, 1, 1]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.zWheel5A_RF_Wheel5A_zWheel5A1_0.geometry}
            material={materials.zWheel5A1}
            position={[0.217, 0, 0]}
            scale={[1.313, 1, 1]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.zWheel5A_RR_Wheel5A_zWheel5A1_0.geometry}
            material={materials.zWheel5A1}
            position={[0.225, 0, 0]}
            scale={[1.313, 1, 1]}
          />
        </group>
      </group>
    </RigidBody>
  );
}

useGLTF.preload("/1970_chevrolet_chevelle_ss_454.glb");
