/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/pokeball.glb -o src/components/Pokeball.jsx -r public 
Author: Vinícius Gabriel (https://sketchfab.com/monambike)
License: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
Source: https://sketchfab.com/3d-models/pokeball-b3e20e3f6ee84c438cd7282e63f38cc2
Title: Pokéball
*/

import { useGLTF } from '@react-three/drei'

export function Pokeball(props) {
  const { nodes, materials } = useGLTF('/pokeball.glb')
  return (
    <group {...props} dispose={null} >
      <group scale={0.025}>
        <group position={[-0.404, 25, -150]} rotation={[-Math.PI / 2,0, 0]}>
          <mesh geometry={nodes.pokeball_belt_Pokeball_Metal_Black_0.geometry} material={materials.Pokeball_Metal_Black} position={[0.773, 0, -0.001]} rotation={[0, 0, -Math.PI / 2]} scale={0.5} />
          <mesh geometry={nodes.pokeball_belt_button_Pokeball_Chrome_White_0.geometry} material={materials.Pokeball_Chrome_White} position={[-22.692, -0.191, -0.001]} rotation={[Math.PI / 2, -Math.PI / 2, 0]} scale={0.5} />
          <mesh geometry={nodes.pokeball_ring_light_Incandescent_Ring_0.geometry} material={materials.Incandescent_Ring} position={[-25.465, -0.191, -0.001]} rotation={[0, Math.PI / 2, 0]} />
          <mesh geometry={nodes.pokeball_shell_bottom_inside_Pokeball_Metal_White__0.geometry} material={materials.Pokeball_Metal_White} position={[0.772, 0, -0.001]} rotation={[0, 0, -Math.PI / 2]} scale={0.5} />
          <mesh geometry={nodes.pokeball_shell_bottom_outside_Pokeball_Metal_White__0.geometry} material={materials.Pokeball_Metal_White} position={[0.772, 0, -0.001]} rotation={[0, 0, -Math.PI / 2]} scale={0.5} />
          <mesh geometry={nodes.pokeball_shell_top_inside_Pokeball_Chrome_White_0.geometry} material={materials.Pokeball_Chrome_White} position={[0.773, -0.011, -0.001]} rotation={[0, 0, -Math.PI / 2]} scale={[0.49, 0.486, 0.486]} />
          <mesh geometry={nodes.pokeball_shell_top_outside_Pokeball_Metal_Red_0.geometry} material={materials.Pokeball_Metal_Red} position={[0.773, 0, -0.001]} rotation={[0, 0, -Math.PI / 2]} scale={0.5} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/pokeball.glb')
