# Stage Number - 1(Backend)
FROM node:20-alpine

WORKDIR /app

COPY package*.json /app

RUN npm install

COPY . /app

CMD [ "node","server.js" ]

# Stage Number - 2(Frontend)

FROM node:20-alpine

WORKDIR /app

COPY package*.json /app

RUN npm install

COPY . /app

RUN npm build